### ISSUE TITLE
Version 3 Plans

### ISSUE THREAD

**Issue by GrahamCampbell** [GrahamCampbell/Analyzer#1]
TODO:

* [ ] Bump minimum PHP to 7.1.3
* [ ] phpdocumentor/reflection-common 2.0.x
* [ ] phpdocumentor/type-resolver 0.7.x
* [ ] phpdocumentor/reflection-docblock 5.x
* [ ] Support phpdoc generic notation

**Comment by jbrooksuk** [comment]
Add the ability to exclude directories within a directory.
